services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: users_db
      MYSQL_TCP_PORT: 3306
    ports: ["3306:3306"]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-prootpw"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  user_service:
    build: ./user_service
    container_name: user_service
    environment:
      DB_URI: "mysql+pymysql://root:rootpw@mysql:3306/users_db"
    depends_on:
      mysql:
        condition: service_healthy
    ports: ["8001:8001"]
    volumes:
      - ./user_service:/app   # maps your flat files to /app

volumes:
  mysql_data:
